title: Vincent Hu
description: I am software engineer from Paris, France. I am passionate about software development, open source and technology in general. I am always looking for new challenges and opportunities to learn new things.
baseurl: ""
url: https://www.vincenthu.net

# change to this theme when testing locally or pushing to GitHub
# theme: cvless
remote_theme: piazzai/cvless

# site settings
taglong: I am software engineer from Paris, France. I am passionate about software development, open source and technology in general. I am always looking for new challenges and opportunities to learn new things.
tagshort: Software Engineer from Paris.

# author settings
author:
  name: Vincent Hu
  email: hu.vincentt@icloud.com
  pin-alt: Dublin, Ireland

# social media links
social:
  github: Viincentt
  instagram: hu_vincent_
  linkedin: huvincent

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
